### ISSUE TITLE
传过来jwt解码异常

### ISSUE THREAD

**Issue by hugoren** [dromara/MaxKey#106]
版本： 3.5.10
部署： docker-compose

jwt有三部组成
header.playload.signature

疑问一：
   maxkey只传了两部分.即header.playload
   场景复现：把“k”改成自已的密钥（随意数据）
   <img width="721" alt="image" src="https://user-images.githubusercontent.com/15722064/207841658-4ffab85d-96fb-4832-8dc2-3530fcb6f243.png">

疑问二：
   header里alg是none
   场景复现：把“k”改成自已的密钥（随意数据）
   <img width="721" alt="image" src="https://user-images.githubusercontent.com/15722064/207841658-4ffab85d-96fb-4832-8dc2-3530fcb6f243.png">

详情如下
<img width="786" alt="image" src="https://user-images.githubusercontent.com/15722064/207833323-512c4523-58f6-4a0f-abb2-3e07ac56595c.png">

**Comment by hugoren** [comment]
对比验证测试，发现改“签名秘钥”这一栏，不同的改动有不同响应。
<img width="749" alt="image" src="https://user-images.githubusercontent.com/15722064/207839764-b4a8249a-4b6d-414b-9fe1-77401063ed39.png">

改动“kid”, maxkey服务端报INTERNAL_SERVER_ERROR!
改动"k", maxkey只传两部分jwt过来，如上面的疑问一。

疑问三：能麻烦提供一下最新样版及参数说明吗？

**Comment by hugoren** [comment]
疑问四：哪个是jwt的signature?
      自查1:signature一般是string, 但从数据库记录来看，是一个text的dict
<img width="774" alt="image" src="https://user-images.githubusercontent.com/15722064/208019207-5fcfffa9-c6ca-4545-97d0-084456cbb3f8.png">
     自查2: 从代码来看是string
     <img width="1082" alt="image" src="https://user-images.githubusercontent.com/15722064/208019394-bd490e06-91d0-4179-840c-22322a8b30b1.png">
     自查3: 这里面kid, k都试了，或是作一个整体都试，都提示signature不对。
    <img width="742" alt="image" src="https://user-images.githubusercontent.com/15722064/208019681-a91416cd-55e3-40d3-bcc5-ce62bcb87b1e.png">

**Comment by hugoren** [comment]
疑问五：
     假设后端接口对jwt认证通过。返回什么数据给maxkey。maxkey又是做了什么动作，让业务web免认证
     看了这些，都没有相关整体链路逻辑介绍
     <img width="1090" alt="image" src="https://user-images.githubusercontent.com/15722064/208020135-eb07616d-869b-4167-afd1-4c8c2b42cb87.png">
<img width="568" alt="image" src="https://user-images.githubusercontent.com/15722064/208020155-796b2c0e-7aeb-4ade-a44b-71c72bcdaec2.png">

**Comment by shimingxy** [comment]
请参照gitee issue
