### ISSUE TITLE
无法使用表单认证

### ISSUE THREAD

**Issue by w38351479** [dromara/MaxKey#109]
想使用表单自动认证提交，但是配置失败
![QQ截图20221227164314](https://user-images.githubusercontent.com/20940470/209639034-216df6e3-ce7b-45d6-bbf0-8ba658b0a98b.png)

**Comment by shimingxy** [comment]
你用的是那个版本？

**Comment by w38351479** [comment]
v3.5.10

**Comment by shimingxy** [comment]
请升级到v3.5.12

**Comment by MangoLab-CC** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dromara/MaxKey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 下午3:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [dromara/MaxKey] 无法使用表单认证 (Issue #109)





 
请升级到v3.5.12
