### ISSUE TITLE
好像不支持认证格式是application/json的方法

### ISSUE THREAD

**Issue by w38351479** [dromara/MaxKey#110]
好像不支持认证格式是application/json的方法
例如：
{"username":"aa","password":"a9f275a070c153543d39ffc9108e3b13"}

**Comment by shimingxy** [comment]
是参数模式

**Comment by w38351479** [comment]
没看到这个协议。

还是说是指，自定义属性？
![image](https://user-images.githubusercontent.com/20940470/210315089-96e2cf62-b26b-45ac-ada8-534e654959c9.png)


MaxKey v3.5.12 GA

**Comment by shimingxy** [comment]
应用的扩展属性
