### ISSUE TITLE
可以每次版本升级的时候提供update的sql吗

### ISSUE THREAD

**Issue by autool** [dromara/MaxKey#111]
如题！
不能每次版本更新都重新弄一次数据库吧？
能把每次数据库更新的部分写一个update吗？
要不每次版本更新的时候都得备份，然后删库，更新数据库。很麻烦不说，数据来回弄，安全性！！！

**Comment by shimingxy** [comment]
这个建议很好

**Comment by sea8u8** [comment]
强烈建议
