### ISSUE TITLE
登录超时设置不生效

### ISSUE THREAD

**Issue by w38351479** [dromara/MaxKey#117]
系统登录后，过10分钟左右就需要重新登陆，配置文件修改了以下两项
maxkey.session.timeout                          =86400
server.servlet.session.timeout                  =86400
redis中有数据，但是好像不生效

**Comment by w38351479** [comment]
web页面中的cookies中的“online_ticket=810838877357998080”，对应Redis中“MXK_SESSION_810838877357998080”，没错吧，TTL值查看是接近86400的，这个是正常，但是还没到过期，前端点击应用就会跳到登录界面

**Comment by shimingxy** [comment]
参照
maxkey.auth.jwt.expires                         =600
