### ISSUE TITLE
Cannot save new password

### ISSUE THREAD

**Issue by PiggyRan** [dromara/MaxKey#126]
MaxKey: 3.5.13

In page `/maxkey/#/config/password` to modify password.

The last line of `确认密码` is not hidden but normal text. It that an issue?

And when I click `保存` button, it fails by prompt '操作失败'。

How can I fix this? Thanks。

**Comment by shimingxy** [comment]
check logs/maxkey.log , that show the  error reason

**Comment by PiggyRan** [comment]
I can't reproduce this since when I access /maxkey/ it shows nothing but some running dot in a blue background. Why? Thanks.

**Comment by PiggyRan** [comment]
I cannot reproduce this issue, close it.
