### ISSUE TITLE
/maxkey/#/passport/login 验证码怎么填，验证码图片也不展示

### ISSUE THREAD

**Issue by geekyouth** [dromara/MaxKey#141]
![image](https://user-images.githubusercontent.com/12899262/236681680-ff3cd079-a987-4c24-92bd-5a7d4fe95095.png)

通过 docker-compose 启动的，初始化 sql 也导入了

**Comment by shimingxy** [comment]
后台报什么错误

**Comment by shimingxy** [comment]
任务时间超期，有问题再重新开启
