### ISSUE TITLE
saml登录confluence，报错could not retrieve IDP config for issuers [http://sso.maxkey.top:9527/sign/saml]

### ISSUE THREAD

**Issue by uamyangel** [dromara/MaxKey#142]
错误信息如下，应用配置中，从没有配置过“http://sso.maxkey.top:9527/sign/saml”这个地址，不知道为啥报这个错误

[impl.web.saml.SamlConsumerServlet] fetchSamlConfigByIssuer IDP initiated SAML flow: could not retrieve IDP config for issuers [http://sso.maxkey.top:9527/sign/saml]

**Comment by shimingxy** [comment]
这个地址不正确

**Comment by uamyangel** [comment]
对的，地址不正确，但我没有配置过这个地址，不知道从哪冒出来的，我怀疑是不是程序里写死的？

**Comment by uamyangel** [comment]
补充一个信息，我是通过docker方式部署的，拉取的最新分支，请问是否需要修改一些默认的配置，以避免上述问题发生？谢谢

**Comment by uamyangel** [comment]
> 这个地址不正确

![6d32ce607412f527fa2943557811209b](https://github.com/dromara/MaxKey/assets/15668052/225cf882-b868-4515-9324-c7819e3674c4)
这是confluence配置

**Comment by shimingxy** [comment]
认证的日志发出来一下

**Comment by uamyangel** [comment]
> 认证的日志发出来一下

这个已经修复正常了。我把过程说一下。

1. 第一次报错could not retrieve IDP config for issuers [http://sso.maxkey.top:9527/sign/saml]，是因为没有配置默认的SERVER_NAME，配置成自己的域名就不报这个错了。
2. 解决1后，发现报错x509证书验证错误，重新生成证书，重新上传配置后，还是这个错误，测试发现，不管怎么更改证书，saml reponse返回的证书都是同一个（不是我生成的任何一个），不知道为啥？
3. 后来没有管x509证书为啥不是自己生成的这个问题，直接copy saml reponse返回的证书，配置到isp中，就全部跑通了，可以正常授权登录了
