### ISSUE TITLE
应用扩展属性，配置后没有生效（生效过，是有缓存？）

### ISSUE THREAD

**Issue by uamyangel** [dromara/MaxKey#144]
应用是saml方式，配置了扩展属性。配置了N次，生效过一次。还原如下：
1、配置扩展属性userGroup=confluence-users。登录重试几次后，接收到的saml response有了userGroup扩展属性。
2、将键名“userGroup”改成“confluence-users”，再去登录，接收到的saml response还是userGroup扩展名，退出登录试了几次都这样，然后去新增了属性attr2=value2，再去登录，没有出现attr2属性。还是只有userGroup属性。

验证：查看了mxk_apps表，扩展属性更改成功了，没有问题。解码saml response没有发现新的扩展属性。

**Comment by uamyangel** [comment]
补充数据库和saml response返回数据
![image](https://github.com/dromara/MaxKey/assets/15668052/42e8eb9b-cfb1-47be-a6fd-e6e01a31bf34)
![image](https://github.com/dromara/MaxKey/assets/15668052/68f0b26b-0448-4117-abfd-ddf273dcf1b5)

**Comment by shimingxy** [comment]
是有缓存，1小时后重新加载，测试环境建议重启

**Comment by uamyangel** [comment]
好的，谢谢
