### ISSUE TITLE
请提供个oidc的springboot的demo

### ISSUE THREAD

**Issue by 2251493330** [dromara/MaxKey#146]
请问可以提供个oidc的springboot的demo吗

**Comment by shimingxy** [comment]
后续会增加

**Comment by 2251493330** [comment]
> 后续会增加

好的谢谢！就在等OIDC了

**Comment by 2251493330** [comment]
> 后续会增加

请问增加好了吗 oidc的springboot的demo

**Comment by shimingxy** [comment]
可以参考https://cloud.tencent.com/developer/article/2226062
