### ISSUE TITLE
支持 AD域账号登录吗？

### ISSUE THREAD

**Issue by huifan** [dromara/MaxKey#161]
支持 AD 域账号登录吗？

**Comment by huifan** [comment]
ldap 配置我已经配置好了，也同步了 ldap 的用户，但是不知道怎么开启 ldap 的用户认证

**Comment by shimingxy** [comment]
需要后台配置LDAP的认证

**Comment by yumu7777777** [comment]
你好，为啥我配置LDAP点测试，老说测试失败
![image](https://github.com/dromara/MaxKey/assets/104643678/7d81fe6b-12b1-49f8-8a66-bb95e4ee9852)
