### ISSUE TITLE
为啥图片上传404

### ISSUE THREAD

**Issue by MrYZhou** [dromara/MaxKey#163]
![image](https://github.com/dromara/MaxKey/assets/44339602/daf92d0c-dba2-4b67-9cd9-87b55b7ac48e)

![image](https://github.com/dromara/MaxKey/assets/44339602/6c54a548-3b67-452c-a763-650cb8a73445)

顺便一提，建议文档和sa-token多学学，讲点原理。多点案例和说明。不然谁知道怎么用。一堆属性在那边。
其次gitee的代码记得及时同步。很多人上不了github.

而且目录结构也很奇葩。到处都是controller.
![image](https://github.com/dromara/MaxKey/assets/44339602/4b3d1fb3-0696-4a04-a34c-1e7324f964e3)

持久层里面还放service.太个性了呀
![image](https://github.com/dromara/MaxKey/assets/44339602/4975136a-14f0-4f3a-a9f8-ee19a16beadd)

**Comment by shimingxy** [comment]
是不是图片太大了

**Comment by MrYZhou** [comment]
> 是不是图片太大了

不是几百kb怎么可以上传不了。不过你说的有可能有道理。2kb的能成功。但是70kb不行。首先我觉得这个bug挺严重的。先不说至少支持10mb以下图片吧。其次这个提示404很有问题。404一般是资源找不到。图片大小限制应该提示更准确点。而且看断点是什么获取是null.

**Comment by shimingxy** [comment]
后续会完善这个功能
