### ISSUE TITLE
Maxkey 接入Harbor OIDC认证， OIDC Endpoint(OIDC服务器地址该怎么填写)

### ISSUE THREAD

**Issue by wzq0824** [dromara/MaxKey#164]
Maxkey 接入Harbor OIDC认证， OIDC Endpoint(OIDC服务器地址该怎么填写)

**Comment by wzq0824** [comment]
尝试将 .well-known/openid-configuration 里的endpoint填写都不行，大佬分享！

**Comment by shimingxy** [comment]
请使用最新版本4.1.x进行测试验证，并重新开新的issue
.well-known/openid-configuration?client_id=xxx
