### ISSUE TITLE
oidc协议接口/sign/api/connect/v10/userinfo，用户信息里面没有email？

### ISSUE THREAD

**Issue by mokewyw** [dromara/MaxKey#175]
我正在集成outline，outline认证需要oidc协议，我在outline的请求scope中写入emai，openid，profile，maxkey会报错email是无效的参数，但是我只写openid和profile，outline会报错返回的profile表单中没有email，我该如何解决

**Comment by mokewyw** [comment]
可不可以在oidc协议获取用户信息的接口里添加email啊

**Comment by shimingxy** [comment]
首先需要正在填写email信息，然后进行正确配置
