### ISSUE TITLE
 OAuth 2.0 应用 跳转失败

### ISSUE THREAD

**Issue by tn1979744292** [dromara/MaxKey#179]
在管理平台新增
OAuth 2.0应用，配置登录地址、回调地址。在认证平台点击应用跳转失败，重定向地址
http://****/sign/authz/oauth/v20/authorize?client_id=931960785171644416&response_type=code&redirect_uri=http%3A%2F%2F192.168.8.19%3A8080%2Fdemon%2Findex.html&approval_prompt=auto

**Comment by shimingxy** [comment]
地址是正确的，服务端替代应用发起了认证请求
