### ISSUE TITLE
新建组织类型为公司时，会覆盖现有内容

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#196]
添加组织的时候，如果新增公司会覆盖掉之前的公司，只展示新创建的公司信息。

**Comment by zxgit139** [comment]
![微信图片_20240229181618](https://github.com/dromara/MaxKey/assets/38752586/1b1aa4e9-2144-48b0-942f-62ce59c78c5d)

**Comment by shimingxy** [comment]
最好不要删除根组织，建议更名

**Comment by zxgit139** [comment]
> 哥们 你是来测试的还是碰瓷的,被你霸版了

确实一次提的有点多....刚开始接触不是很了解，很多问题都能合并成一个问题
