### ISSUE TITLE
新增组织，组织编码相同创建成功

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#197]
身份管理->组织->新增，新增组织信息情况下编码和名字的数据可以重复添加
![微信截图_20240301160623](https://github.com/dromara/MaxKey/assets/38752586/030f5b73-0c0b-48e1-81fc-c2386146ba63)

**Comment by shimingxy** [comment]
数据都是从ehr同步，这里不做检验

**Comment by zxgit139** [comment]
> 数据都是从ehr同步，这里不做检验

了解
