### ISSUE TITLE
用户，左侧树选择一级，未显示整个所有用户信息

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#201]
只显示一条数据的信息
![微信图片_20240229184100](https://github.com/dromara/MaxKey/assets/38752586/bc5cacfa-9f13-4312-8066-a2dda177cd33)

**Comment by shimingxy** [comment]
菜单树只显示一级组织下用户数据

**Comment by zxgit139** [comment]
> 菜单树只显示一级组织下用户数据

了解
