### ISSUE TITLE
密码修改后提示操作失败

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#203]
身份管理->用户->操作选项->修改密码, 修改提示操作失败
![微信图片_20240229184308](https://github.com/dromara/MaxKey/assets/38752586/04fdb8c5-8a88-4e0b-a879-15e6213e3da3)

**Comment by shimingxy** [comment]
请更新最新代码

**Comment by zxgit139** [comment]
> 请更新最新代码

好的
