### ISSUE TITLE
新增用户组，必填项为空创建成功

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#204]
用户组新增信息，未填写必填信息，创建成功了，空白的数据
![微信截图_20240229184801](https://github.com/dromara/MaxKey/assets/38752586/911fcf1e-b700-486c-91e1-814887d4a2b0)

**Comment by shimingxy** [comment]
后续优化，你自己增加校验功能

**Comment by zxgit139** [comment]
> 后续优化，你自己增加校验功能

了解
