### ISSUE TITLE
OAuth2.x 协议新增，默认参数直接提交报404

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#205]
应用管理创建应用，oauth举例，默认直接提交保存，不填写相关必填信息会提示404
![微信截图_20240229184941](https://github.com/dromara/MaxKey/assets/38752586/6fd6f989-1559-48a1-9fe6-b5e4b88d3be9)

**Comment by shimingxy** [comment]
请更新到最新版本

**Comment by zxgit139** [comment]
> 请更新到最新版本

好的
