### ISSUE TITLE
OAuth 2.0 协议新增图标上传后下载无反应

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#206]
鼠标悬停在头像的时候，中间的下载功能点击就跳转到一个空白页面，不进行下载
![微信截图_20240229185036](https://github.com/dromara/MaxKey/assets/38752586/bcdc8d72-0519-4949-adb6-f3f03425d53c)

**Comment by shimingxy** [comment]
目前只能查看

**Comment by zxgit139** [comment]
> 目前只能查看

![1472F72F](https://github.com/dromara/MaxKey/assets/38752586/577e5ef8-23f7-42d5-86ef-8d0792025539)
