### ISSUE TITLE
身份管理-组织，添加顶级公司的会有覆盖问题

### ISSUE THREAD

**Issue by zxgit139** [dromara/MaxKey#207]
没新增之前的原始数据顶级公司是马克思钥匙，点击新增按钮，按照页面填写相关信息，选择公司类型为公司，会覆盖前一个马克思钥匙的公司数据,并只展示新增的公司数据信息
![微信截图_20240229185313](https://github.com/dromara/MaxKey/assets/38752586/32e2aff7-7728-4b24-aa11-7fe288d0b0bb)

**Comment by zxgit139** [comment]
之前的原始数据
![微信图片_20240229190215](https://github.com/dromara/MaxKey/assets/38752586/328be8a4-2cdd-4146-80dc-7b37d69911b0)

**Comment by shimingxy** [comment]
最好在原来的基础上修改，或者从ehr同步数据

**Comment by zxgit139** [comment]
> 最好在原来的基础上修改，或者从ehr同步数据

了解
