### ISSUE TITLE
管理后台登录立刻显示“未登录或登录已过期”

### ISSUE THREAD

**Issue by clyce** [dromara/MaxKey#215]
后台管理页面（maxkey-mgt），管理员账户（用户名密码正确）登录后，进入控制台而后瞬间跳回登录页面，显示未登录或登录已过期。
![image](https://github.com/dromara/MaxKey/assets/1068472/551cc1f3-176a-433d-a63d-ba3f4a699bf5)

用户端可以正常使用。

**Comment by shimingxy** [comment]
可以把会话和token的时间加长
