### ISSUE TITLE
sql中的data数据无法导入

### ISSUE THREAD

**Issue by ArronYR** [dromara/MaxKey#234]
clone项目到本地，并在本地MySQL中创建好db，将sql文件夹下的`maxkey.sql`表结构导入，然后选择`maxkey_data.sql`导入数据，提示
```
读取文件时发生错误，因为您选择的文本编码（自动检测 - Unicode (UTF-8)）无法读取该文件。
```
<img width="260" alt="image" src="https://github.com/user-attachments/assets/620de9a2-72db-4f54-b400-bd14afdfab2d">

使用vscode编辑器打开该文件，显示乱码：
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/b3098446-b788-4e5b-b955-a5a41ebad743">

请问大家是解决该问题？

**Comment by shimingxy** [comment]
请从https://maxkey.top/zh/about/download.html下载，windows版本，通过工具同步到新的环境
