### ISSUE TITLE
jib构建docker镜像时报错

### ISSUE THREAD

**Issue by Rebellioncry** [dromara/MaxKey#45]
A problem was found with the configuration of task ':maxkey-web-maxkey:jibBuildTar' (type 'BuildTarTask').
  - Type 'BuildTarTask' property 'jib.container.expandClasspathDependencies' of type boolean shouldn't be annotated with @Optional.

这是jib的bug导致的，已经被官方解决了，升级到2.7.1+就解决了
https://github.com/GoogleContainerTools/jib/issues/2930

**Comment by shimingxy** [comment]
fixed
