### ISSUE TITLE
所有的单点登录都需要经过内置的登陆页吗？

### ISSUE THREAD

**Issue by Rebellioncry** [dromara/MaxKey#50]
我现在使用oauth2.0协议，不管用哪种模式，都会跳转登陆页。导致用postman的方式请求token成为不可能，我看了后端代码，你们所有的认证返回都是ModelAndView，居然没有api的形式吗？这样符合oauth2.0协议规范吗？还有，oauth2.0的client credentials模式好像也没有，如图：
![捕获](https://user-images.githubusercontent.com/31620265/116333355-e24e0980-a805-11eb-8961-5aad36e09914.PNG)
其中的token是什么？id_token是给oidc用的吗？真的很不解，求解答！

**Comment by shimingxy** [comment]
有password的模式
https://github.com/MaxKeyTop/MaxKey-Client-sdk/blob/master/src/test/java/org/maxkey/client/oauth/test/MaxkeyPasswordDemo.java
