### ISSUE TITLE
新增用户无法输入手机号

### ISSUE THREAD

**Issue by MemoryF** [dromara/MaxKey#68]
前后台管理系统都存在。
无法书屋手机号，编辑也是。
<img width="984" alt="image" src="https://user-images.githubusercontent.com/26829986/176332061-3406afc2-a0f2-4c26-a6bc-1a23e463f0d5.png">

**Comment by shimingxy** [comment]
代码已经更新，手机号及工号
https://github.com/dromara/MaxKey/commit/8bfdaa33c084dfbe2b969617c324e1621c46022d
