### ISSUE TITLE
3.5.1版本saml2.0问题

### ISSUE THREAD

**Issue by ggfzx** [dromara/MaxKey#69]
1.maxkey的metadata在哪里下载
2.上传第三方应用的metadata时，出现错误
![image](https://user-images.githubusercontent.com/86279656/177491165-7070c03f-6949-446d-afb6-f2bb04afb71b.png)
3.编辑已存在的saml应用，重新上传metadata，直接跳出显示更新成功，无法上传

**Comment by shimingxy** [comment]
需要选择上传的文件类型，证书或者元数据(metadata XML)

**Comment by ggfzx** [comment]
选择后上传，出现这个错误
