### ISSUE TITLE
AppService.get方法查询sql却是查询mxk_ldap_context表，导致查询为空

### ISSUE THREAD

**Issue by zhanghuimin00136** [dromara/MaxKey#74]
操作过程：启动后端web 端口9527，启动web前端 端口8527。通过前端登录进入主页，在主页的应用中随意选择一个，会打开一个页面，但是报 INTERNAL_SERVER_ERROR!。后台日志显示因为查询app为空，然后将app放入缓存时报错，因为放入缓存需要app不为空。而app为空的原因是不查询app表而去查询ldap_conetext表。
![image](https://user-images.githubusercontent.com/45162622/186598932-b11391ad-1609-4486-a344-9bff4ccffaae.png)

重启后端服务，但是不登录，而是直接访问app的链接 `http://localhost:8527/sign/authz/41065fe3-ae67-4172-a460-fd0079e88294`，此时查询语句正常。

**Comment by shimingxy** [comment]
请更新源代码，该问题由于jar升级导致，jar包升级

**Comment by shimingxy** [comment]
仓库评论有提到这个问题，https://gitee.com/dromara/MaxKey
