### ISSUE TITLE
有saml2.0对接zabbix成功的朋友吗

### ISSUE THREAD

**Issue by w38351479** [dromara/MaxKey#77]
如有的话，方便提供一下配置截图吗，隐私部分打码就好，我一直没配置成功，跳转不过去

**Comment by shimingxy** [comment]
你可以加官方qq，把实际情况说明一下，我们协助你解决

**Comment by shimingxy** [comment]
请把issue补充完整，加官方QQ：1054466084，由于长时间没有反馈，先close
