### ISSUE TITLE
Add jwt token_format support for tokenEndpoint

### ISSUE THREAD

**Issue by travelersun** [dromara/MaxKey#80]
Can add jwt token_format support for tokenEndpoint ? 
just like the uaa project https://github.com/cloudfoundry/uaa.git
api docs https://docs.cloudfoundry.org/api/uaa/version/76.1.0/index.html#authorization-code-grant-2

Parameter token_format:
token_format | String | Optional | Can be set to opaque to retrieve an opaque and revocable token or to jwt to retrieve a JWT token. If not set the zone setting config.tokenPolicy.jwtRevocable is used.

So that the jwt access_token can valid itself and retrieve userinfo without request to authorization server userinfo endpoint until it expired.

**Comment by shimingxy** [comment]
We are considering your suggestion，scopes can contain id_token， which is JWT used self sign
