### ISSUE TITLE
可以不以在应用界面加一个分类

### ISSUE THREAD

**Issue by ddddl-cn** [dromara/MaxKey#81]
可以不以在应用界面加一个分类
应用
![image](https://user-images.githubusercontent.com/25097682/197663274-9f5fdc75-7841-4b45-8ba1-8dbbd97c8b7e.png)

**Comment by shimingxy** [comment]
后台已经有分类和是否常规应用，这块你可以自己改一下，后续的版本会在增加显示分类的功能

**Comment by ddddl-cn** [comment]
后台的分类可以区分，前台无法区分。有些可以接入，有些正在接入，然后未接入图标是灰色的不可点击。

**Comment by shimingxy** [comment]
https://github.com/dromara/MaxKey/commit/bf413e40149a438718463c918f6b99873f88d6dd
