### ISSUE TITLE
启动失败，乱码

### ISSUE THREAD

**Issue by ddddl-cn** [dromara/MaxKey#82]
![image](https://user-images.githubusercontent.com/25097682/197939122-fa9c6381-1a17-4be0-9f73-c9825548d44b.png)
![image](https://user-images.githubusercontent.com/25097682/197939179-9479b7d2-223c-47a4-8478-8ac8a51536b7.png)

**Comment by shimingxy** [comment]
把字符编码设置成UTF8解决该问题
