### ISSUE TITLE
修改应用"登录地址"无效

### ISSUE THREAD

**Issue by stdnt-xiao** [dromara/MaxKey#83]
通过docker-compose部署maxkey的latest版本
在后台管理界面修改『有道云笔记』应用的登录地址为『Maxkey』的登录地址（仅测试功能）
修改后，重新登录还是会跳转到有道云
![image](https://user-images.githubusercontent.com/20313983/200708879-1b38bfa1-1aa3-49fa-89eb-ca24136b066b.png)

另外有微信讨论群？

**Comment by shimingxy** [comment]
生产环境通常是不会发生变化的，MaxKey缓存了应用信息以提高效率，有效时间是30分钟，或者重新认证系统

**Comment by shimingxy** [comment]
可以加官方qq1054466084
