### ISSUE TITLE
添加表单认证方式后台出现credential字段格式错误

### ISSUE THREAD

**Issue by stdnt-xiao** [dromara/MaxKey#86]
错误日志如下:

maxkey-mgt  | 2022-11-09 15:43:51.244 DEBUG [http-nio-9526-exec-10] org.maxkey.authn.jwt.AuthJwtService:127 - JWT Validate true
maxkey-mgt  | 2022-11-09 15:43:51.246 WARN  [http-nio-9526-exec-10] org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver:208 - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize value of type `int` from String "user-defined": not a valid `int` value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `int` from String "user-defined": not a valid `int` value<EOL> at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 475] (through reference chain: org.maxkey.entity.apps.AppsFormBasedDetails["credential"])]
maxkey-mgt  | 2022-11-09 15:43:51.251 DEBUG [http-nio-9526-exec-10] org.maxkey.web.ExceptionEndpoint:41 - Exception BAD_REQUEST
maxkey-mgt  | 2022-11-09 15:43:51.261 WARN  [http-nio-9526-exec-10] org.springframework.web.servlet.PageNotFound:1282 - No mapping for POST /maxkey-mgt-api/exception/error/exception/400

![image](https://user-images.githubusercontent.com/20313983/200768786-4c50f796-943b-4a14-8050-91ef7ab7ed6c.png)

**Comment by shimingxy** [comment]
最新的数据库SQL还没有提交，在3.5.10发布

**Comment by stdnt-xiao** [comment]
@shimingxy 
我是用docker3.5.9版本部署的，他需要使用3.5.10版本的sql？目前有最新sql库在maxkey代码？

**Comment by naah69** [comment]
> 最新的数据库SQL还没有提交，在3.5.10发布

运行了这个sql，依然有问题，数据库里是tinyint，但是服务内传过来是字符串

https://gitee.com/dromara/MaxKey/blob/main/docker/docker-mysql/docker-entrypoint-initdb.d/v3.5.10.ga/maxkey_v3.5.10.GA.sql

<img width="686" alt="image" src="https://user-images.githubusercontent.com/25682169/205213613-c426c500-dade-46bb-b381-13c8196b3d78.png">

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/25682169/205213650-faaa98d2-1d5e-49a8-8834-e1072c9ecfb4.png">

**Comment by shimingxy** [comment]
数据库改成varchar类型
