### ISSUE TITLE
有没有相关demo，要不然不知道从何入手改造旧系统接入

### ISSUE THREAD

**Issue by 852675742** [dromara/MaxKey#90]
请问有没有相关demo，要不然不知道从何入手使用maxkey改造旧系统接入

**Comment by shimingxy** [comment]
可以参照官方文档
https://maxkey.top/zh/am/sso/oauth2.html
https://maxkey.top/zh/am/sso/jwt.html
https://maxkey.top/zh/am/sso/oidc.html
https://maxkey.top/zh/am/sso/cas.html
