### ISSUE TITLE
配置jenkins整个链路没通，显示cas server 不识别，返回 not registered .

### ISSUE THREAD

**Issue by hugoren** [dromara/MaxKey#97]
maxkey版本: 3.5.9
部署方式: docker compose
问题： jenkins配置cas server 不识别
<img width="340" alt="image" src="https://user-images.githubusercontent.com/15722064/203293381-1c1b6a61-4fde-4558-8517-ec9a6c477f71.png">
          直接用回调地址测试，返回 not registered .
<img width="313" alt="image" src="https://user-images.githubusercontent.com/15722064/203293591-0aab1426-f9f2-4238-b092-4193f76a4174.png">
谢谢回答

**Comment by hugoren** [comment]
jenkins 集成指南，也返回看了，没发现是哪个环节配错了
https://maxkey.top/zh/am/inteapps/MaxKey%E4%B8%8EJenkins%E5%8D%95%E7%82%B9%E7%99%BB%E5%BD%95%E9%9B%86%E6%88%90%E6%8C%87%E5%8D%97v2.0.pdf

**Comment by shimingxy** [comment]
请参考https://gitee.com/dromara/MaxKey/issues/I5ZBOB，文档后续会陆续更新。

**Comment by lihumzsan** [comment]
> 请参考[https://gitee.com/dromara/MaxKey/issues/I5ZBOB，文档后续会陆续更新。](https://gitee.com/dromara/MaxKey/issues/I5ZBOB%EF%BC%8C%E6%96%87%E6%A1%A3%E5%90%8E%E7%BB%AD%E4%BC%9A%E9%99%86%E7%BB%AD%E6%9B%B4%E6%96%B0%E3%80%82)



这个链接返回404

**Comment by shimingxy** [comment]
https://gitee.com/dromara/MaxKey/issues/I5ZBOB
