### ISSUE TITLE
组织管理删除失败 String index out of range

### ISSUE THREAD

**Issue by hugoren** [dromara/MaxKey#99]
版本： 3.5.9
部署方式： docker-compose
问题： 
<img width="965" alt="image" src="https://user-images.githubusercontent.com/15722064/203488520-6fbf9855-d3b7-4e2f-b665-95bb89ef815f.png">

日志：  Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

**Comment by shimingxy** [comment]
选择组织树的节点是在右边该节点的子级组织列表，需要选择列表中的复选框才能删除

**Comment by hugoren** [comment]
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/15722064/203678508-f2e8a255-53b4-4fd5-a957-40fd39cb044c.png">

**Comment by hugoren** [comment]
也不应该在程序中有String index out of range: -1这种异常
代码上可避免。
以上仅是个人浅学的建议
